DROP TABLE TASR23B03_BI.CAR_ACCNTS_RECEIVABLE_OVERVIEW;

CREATE MULTISET TABLE TASR23B03_BI.CAR_ACCNTS_RECEIVABLE_OVERVIEW,
    NO FALLBACK ,
    NO BEFORE JOURNAL,
    NO AFTER JOURNAL,
    CHECKSUM = DEFAULT,
    DEFAULT MERGEBLOCKRATIO
    (
      TAS_SOURCE_ID VARCHAR(10) CHARACTER SET UNICODE CASESPECIFIC NOT NULL,
      COMPANY_ID CHAR(4) CHARACTER SET UNICODE CASESPECIFIC,
      BUSINESS_AREA_ID CHAR(4) CHARACTER SET UNICODE CASESPECIFIC,
      CURRENCY_ID VARCHAR(5) CHARACTER SET UNICODE CASESPECIFIC,
      CUSTOMER_ID VARCHAR(10) CHARACTER SET UNICODE CASESPECIFIC,
      CUSTOMER_PAYER_ID VARCHAR(10) CHARACTER SET UNICODE CASESPECIFIC,
      FINANCIAL_ACCOUNT_ID VARCHAR(10) CHARACTER SET UNICODE CASESPECIFIC,
      FA_DOCUMENT_DATE DATE FORMAT 'YY/MM/DD',
      FA_VALID_TO_DATE DATE FORMAT 'YY/MM/DD',
      CONTROLLING_AREA_ID CHAR(4) CHARACTER SET UNICODE CASESPECIFIC,
      COST_CENTER_ID VARCHAR(10) CHARACTER SET UNICODE CASESPECIFIC,
      CC_VALID_TO_DATE DATE FORMAT 'YY/MM/DD',
      POSTING_DATE DATE FORMAT 'YY/MM/DD',
      PROJECT_ITEM_ID VARCHAR(8) CHARACTER SET UNICODE CASESPECIFIC,
      CREDIT_CONTROL_AREA_ID CHAR(4) CHARACTER SET UNICODE CASESPECIFIC,
      TRANSACTION_STATUS_ID VARCHAR(7) CHARACTER SET UNICODE NOT CASESPECIFIC,
      DEBIT_CREDIT_ID CHAR(1) CHARACTER SET UNICODE CASESPECIFIC,
      FINANCIAL_DOCUMENT_ID CHAR(2) CHARACTER SET UNICODE CASESPECIFIC,
      ACCOUNTING_DOCUMENT_ID VARCHAR(10) CHARACTER SET UNICODE CASESPECIFIC NOT NULL,
      ACCOUNTING_DOCUMENT_ITEM_ID CHAR(3) CHARACTER SET UNICODE CASESPECIFIC,
      FISCAL_YEAR_NUMBER CHAR(4) CHARACTER SET UNICODE CASESPECIFIC,
      FISCAL_PERIOD_NUMBER CHAR(2) CHARACTER SET UNICODE CASESPECIFIC,
      TIME_DATE DATE FORMAT 'YY/MM/DD',
      AMOUNT DECIMAL(15,2),
      OPEN_AMOUNT DECIMAL(15,2),
      CLEARED_AMOUNT DECIMAL(15,2),
      CURRENTLY_OPEN_AMOUNT DECIMAL(15,2),
      CURRENTLY_CLEARED_AMOUNT DECIMAL(15,2),
      CURRENTLY_LATE_AMOUNT DECIMAL(15,2),
      CURRENTLY_OPEN_PAST_DUE_AMOUNT DECIMAL(15,2),
      TRANSACTION_COUNT DECIMAL(38,0),
      CURRENTLY_OPEN_DAYS DECIMAL(38,0),
      CURRENTLY_OPEN_LATE_DAYS DECIMAL(38,0),
      CURRENTLY_OPEN_UNTIL_DUE_DAYS DECIMAL(38,0),
      DAYS_TO_CLOSURE DECIMAL(15,2),
      PRIMARY KEY(TAS_SOURCE_ID,ACCOUNTING_DOCUMENT_ID)
    )
PRIMARY INDEX(ACCOUNTING_DOCUMENT_ID);


